### ISSUE TITLE
Craft 5?

### ISSUE THREAD

**Issue by Tim-Wils** [oof-bar/craft-twig-toolbox#2]
Hi!

This is a great plugin that we use a lot for Craft 4, but is there any chance this plugin will be ported to Craft 5 anytime soon?

**Comment by AugustMiller** [comment]
Oh my gosh. I thought I had already taken care of this! I’ll cut a release today. 🫶

**Comment by AugustMiller** [comment]
Ok, 1.1.0 is out with the relaxed version constraint that allows it to be installed in Craft 4 and Craft 5!

https://plugins.craftcms.com/twig-toolbox?craft5
